/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V3.2.0
 * Contact: avishay@flexi-core.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicCreate } from '@flexicore/flexicore-client/dist/model/basicCreate';


export interface CreateGridPreset extends BasicCreate { 
    relatedClassCanonicalName?: string;
    dynamicExecutionId?:string;
    latMapping?:string;
    lonMapping?:string;
}