/**
 * REST API for Flexicore filtered by your access rights
 * Flexicore REST API
 *
 * OpenAPI spec version: V1.1.0
 * Contact: avishaybennatan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LinkUiFieldRequest { 
    clazzName?: string;
    uiFieldId?: string;
    priority?: number;
    context?: string;
    visible?: boolean;
    categoryName?:string;
    displayName?:string;
}
